# Generated by Django 3.2.16 on 2023-05-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
